name: CI
on: [push, pull_request]
env:
  CCACHE_DIR: $HOME/.ccache
  sample_c: |
    #include <stdio.h>
    int main(void) {
      printf("Joker is geh\n");
    }

jobs:
  ccache:
    runs-on: ubuntu-18.04
   
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ccache gcc

      - name: "CCACHE TEST"
        run: |
          echo ${{ env.sample_c }} >> temp.c
          sudo -E /usr/lib/ccache/gcc ./temp.c
          sudo -E ccache -s
          ls -la $HOME
