name: CI
on: [push, pull_request]
env:
  base_script: |
    pwd
    cd $HOME/another_dir
    pwd

jobs:
  build:
    runs-on: ubuntu-18.04
   
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
 
      - name: "Permissions"
        run: |
          chmod +x $GITHUB_WORKSPACE/.github/workflows/base_script.sh

      - name: "Step 1"
        run: |
          mkdir -p $HOME/another_dir
          cd $HOME/another_dir
          pwd
          export VAR1="$(pwd)"
    
      - name: "Using variable from last step"
        run: |
          pwd
          cd ${VAR1}
          pwd

      - name: "Base script env"
        run: |
          eval "$base_script"
          mkdir -p $GITHUB_WORKSPACE/Build/linux/
          cd $GITHUB_WORKSPACE/Build/linux/
          eval "$base_script"

      - name: "Base script file"
        run: |
           $GITHUB_WORKSPACE/.github/workflows/base_script.sh
           mkdir -p $GITHUB_WORKSPACE/Build/Linux/
           cd $GITHUB_WORKSPACE/Build/Linux/
           $GITHUB_WORKSPACE/.github/workflows/base_script.sh

      - name: Prepare cache hash
        id: cache_hash
        run: |
          echo "::set-output name=hash::${{ hashFiles('**/*.yml') }}"

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: .
          key: cache-${{ steps.cache_hash.outputs.hash }}
          restore-keys: |
            cache-
            
      - name: This will fail
        id: failure_test
        continue-on-error: true
        run: |
          echo "value1" > value1.txt
          echo "value1" > value2.txt
          diff value1.txt value2.txt
          echo ::set-output name=status::success

      - name: Create artifact
        if: steps.failure_test.outputs.status != 'success'
        run: tar czf ./value.tar.gz value*
        
      - name: On fail, upload artifact SVT-AV1 (master)
        if: steps.failure_test.outputs.status != 'success'
        uses: actions/upload-artifact@v1
        with:
          name: value
          path: ./value.tar.gz
