name: CI
on: [push, pull_request]
env:
  base_script: |
    pwd
    cd $HOME/another_dir
    pwd

jobs:
  build:
    runs-on: ubuntu-18.04
   
    steps:
      - name: "Step 1"
        run: |
          mkdir -p $HOME/another_dir
          cd $HOME/another_dir
          pwd
          export VAR1="$(pwd)"
    
      - name: "Using variable from last step"
        run: |
          pwd
          cd ${VAR1}
          pwd

      - name: "Base script env"
        run: |
          eval "$base_script"
          mkdir -p $GITHUB_WORKSPACE/Build/linux/
          cd $GITHUB_WORKSPACE/Build/linux/
          eval "$base_script"

      - name: "Base script file"
        run: |
           $GITHUB_WORKSPACE/.github/workflows/base_script.sh
