name: CI
on: [push, pull_request]
env:
  base_script: |
    pwd
    cd $HOME/another_dir
    pwd

jobs:
  build:
    runs-on: ubuntu-18.04
   
    steps:
      - name: "Step 1"
        run: |
          mkdir -p $HOME/another_dir
          cd $HOME/another_dir
          pwd
          export VAR1="$(pwd)"
    
      - name: "Step 2"
        run: |
          pwd
          cd ${VAR1}
          pwd

      - name: "Base script"
        run: |
          eval "$base_script"
